# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\"\x06\n\x04void\"\"\n\x03Msg\x12\x0e\n\x06source\x18\x01 \x01(\r\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x12\n\x03Res\x12\x0b\n\x03res\x18\x02 \x01(\t2#\n\x06\x44\x65moFL\x12\x19\n\tbroadcast\x12\x04.Msg\x1a\x04.Res\"\x00\x62\x06proto3')



_VOID = DESCRIPTOR.message_types_by_name['void']
_MSG = DESCRIPTOR.message_types_by_name['Msg']
_RES = DESCRIPTOR.message_types_by_name['Res']
void = _reflection.GeneratedProtocolMessageType('void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'demo_pb2'
  # @@protoc_insertion_point(class_scope:void)
  })
_sym_db.RegisterMessage(void)

Msg = _reflection.GeneratedProtocolMessageType('Msg', (_message.Message,), {
  'DESCRIPTOR' : _MSG,
  '__module__' : 'demo_pb2'
  # @@protoc_insertion_point(class_scope:Msg)
  })
_sym_db.RegisterMessage(Msg)

Res = _reflection.GeneratedProtocolMessageType('Res', (_message.Message,), {
  'DESCRIPTOR' : _RES,
  '__module__' : 'demo_pb2'
  # @@protoc_insertion_point(class_scope:Res)
  })
_sym_db.RegisterMessage(Res)

_DEMOFL = DESCRIPTOR.services_by_name['DemoFL']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOID._serialized_start=14
  _VOID._serialized_end=20
  _MSG._serialized_start=22
  _MSG._serialized_end=56
  _RES._serialized_start=58
  _RES._serialized_end=76
  _DEMOFL._serialized_start=78
  _DEMOFL._serialized_end=113
# @@protoc_insertion_point(module_scope)
