# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import demo_pb2 as demo__pb2


class DemoFLStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.broadcast = channel.unary_unary(
                '/DemoFL/broadcast',
                request_serializer=demo__pb2.Msg.SerializeToString,
                response_deserializer=demo__pb2.Res.FromString,
                )


class DemoFLServicer(object):
    """Missing associated documentation comment in .proto file."""

    def broadcast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DemoFLServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'broadcast': grpc.unary_unary_rpc_method_handler(
                    servicer.broadcast,
                    request_deserializer=demo__pb2.Msg.FromString,
                    response_serializer=demo__pb2.Res.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DemoFL', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DemoFL(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def broadcast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DemoFL/broadcast',
            demo__pb2.Msg.SerializeToString,
            demo__pb2.Res.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
