# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import fedpred_pb2 as fedpred__pb2


class FedPredStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.keyex = channel.unary_unary(
                '/FedPred/keyex',
                request_serializer=fedpred__pb2.HelloMsg.SerializeToString,
                response_deserializer=fedpred__pb2.HelloRes.FromString,
                )
        self.enc_msg = channel.unary_unary(
                '/FedPred/enc_msg',
                request_serializer=fedpred__pb2.EncMsg.SerializeToString,
                response_deserializer=fedpred__pb2.EncMsg.FromString,
                )


class FedPredServicer(object):
    """Missing associated documentation comment in .proto file."""

    def keyex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def enc_msg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FedPredServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'keyex': grpc.unary_unary_rpc_method_handler(
                    servicer.keyex,
                    request_deserializer=fedpred__pb2.HelloMsg.FromString,
                    response_serializer=fedpred__pb2.HelloRes.SerializeToString,
            ),
            'enc_msg': grpc.unary_unary_rpc_method_handler(
                    servicer.enc_msg,
                    request_deserializer=fedpred__pb2.EncMsg.FromString,
                    response_serializer=fedpred__pb2.EncMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FedPred', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FedPred(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def keyex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FedPred/keyex',
            fedpred__pb2.HelloMsg.SerializeToString,
            fedpred__pb2.HelloRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def enc_msg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FedPred/enc_msg',
            fedpred__pb2.EncMsg.SerializeToString,
            fedpred__pb2.EncMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
