# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedpred.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfedpred.proto\"\x06\n\x04void\"+\n\x04Sign\x12\n\n\x02\x63t\x18\x01 \x01(\x0c\x12\n\n\x02pk\x18\x02 \x01(\x0c\x12\x0b\n\x03msg\x18\x03 \x01(\x0c\"*\n\x08HelloMsg\x12\x13\n\x04sign\x18\x01 \x01(\x0b\x32\x05.Sign\x12\t\n\x01r\x18\x02 \x01(\r\"\x15\n\x08HelloRes\x12\t\n\x01r\x18\x01 \x01(\r\"$\n\x06\x45ncMsg\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\n\n\x02\x63t\x18\x02 \x01(\x0c\x32I\n\x07\x46\x65\x64Pred\x12\x1f\n\x05keyex\x12\t.HelloMsg\x1a\t.HelloRes\"\x00\x12\x1d\n\x07\x65nc_msg\x12\x07.EncMsg\x1a\x07.EncMsg\"\x00\x62\x06proto3')



_VOID = DESCRIPTOR.message_types_by_name['void']
_SIGN = DESCRIPTOR.message_types_by_name['Sign']
_HELLOMSG = DESCRIPTOR.message_types_by_name['HelloMsg']
_HELLORES = DESCRIPTOR.message_types_by_name['HelloRes']
_ENCMSG = DESCRIPTOR.message_types_by_name['EncMsg']
void = _reflection.GeneratedProtocolMessageType('void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'fedpred_pb2'
  # @@protoc_insertion_point(class_scope:void)
  })
_sym_db.RegisterMessage(void)

Sign = _reflection.GeneratedProtocolMessageType('Sign', (_message.Message,), {
  'DESCRIPTOR' : _SIGN,
  '__module__' : 'fedpred_pb2'
  # @@protoc_insertion_point(class_scope:Sign)
  })
_sym_db.RegisterMessage(Sign)

HelloMsg = _reflection.GeneratedProtocolMessageType('HelloMsg', (_message.Message,), {
  'DESCRIPTOR' : _HELLOMSG,
  '__module__' : 'fedpred_pb2'
  # @@protoc_insertion_point(class_scope:HelloMsg)
  })
_sym_db.RegisterMessage(HelloMsg)

HelloRes = _reflection.GeneratedProtocolMessageType('HelloRes', (_message.Message,), {
  'DESCRIPTOR' : _HELLORES,
  '__module__' : 'fedpred_pb2'
  # @@protoc_insertion_point(class_scope:HelloRes)
  })
_sym_db.RegisterMessage(HelloRes)

EncMsg = _reflection.GeneratedProtocolMessageType('EncMsg', (_message.Message,), {
  'DESCRIPTOR' : _ENCMSG,
  '__module__' : 'fedpred_pb2'
  # @@protoc_insertion_point(class_scope:EncMsg)
  })
_sym_db.RegisterMessage(EncMsg)

_FEDPRED = DESCRIPTOR.services_by_name['FedPred']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOID._serialized_start=17
  _VOID._serialized_end=23
  _SIGN._serialized_start=25
  _SIGN._serialized_end=68
  _HELLOMSG._serialized_start=70
  _HELLOMSG._serialized_end=112
  _HELLORES._serialized_start=114
  _HELLORES._serialized_end=135
  _ENCMSG._serialized_start=137
  _ENCMSG._serialized_end=173
  _FEDPRED._serialized_start=175
  _FEDPRED._serialized_end=248
# @@protoc_insertion_point(module_scope)
